return { }

-- return {
--   {
--     "mfussenegger/nvim-dap",
--     dependencies = {
--       "rcarriga/nvim-dap-ui",
--       "theHamsta/nvim-dap-virtual-text",
--     },
--     config = function()
--       local dap = require("dap")
--       local dapui = require("dapui")
--
--       dapui.setup()
--       require("nvim-dap-virtual-text").setup()
--
--       dap.listeners.after.event_initialized["dapui_config"] = function() dapui.open() end
--       dap.listeners.before.event_terminated["dapui_config"] = function() dapui.close() end
--       dap.listeners.before.event_exited["dapui_config"] = function() dapui.close() end
--
--       -- Example: attach to IIS Express
--       dap.adapters.coreclr = {
--         type = "executable",
--         command = "C:/Users/orope/.local/vsdbg/vsdbg.exe",
--         args = { "--interpreter=vscode" },
--       }
--
--       dap.configurations.cs = {
--         {
--           type = "coreclr",
--           name = "Attach to IIS Express",
--           request = "attach",
--           processId = require("dap.utils").pick_process,
--           cwd = "C:/Users/orope/Documents/hc/src",
--           program = "C:/Users/orope/Documents/hc/src/HC.RestService/obj/Debug/HC.RestService.dll",
--         },
--       }
--     end,
--   },
-- }
